#pragma once
#include <units/time.h>

#define SOLENOIDSETLENGTH 3_ms;

enum ArmConstants {
	SHOOTERMOTOR1ID = 6,
	SHOOTERMOTOR2ID = 7,

	SHOOTERSOLENOIDFORWARDID = 0,
	SHOOTERSOLENOIDREVERSEID = 1,

	CLIMBERSOLENOIDFORWARDID = 4,
	CLIMBERSOLENOIDREVERSEID = 5
};

enum ArmAngleConstants {
	ANGLEMOTOR1ID = 10,
	ANGLEMOTOR2ID = 11
};

enum DrivetrainConstants {
	FRONTRIGHTID = 2,
	FRONTLEFTID = 1,
	BACKRIGHTID = 3,
	BACKLEFTID = 0
};